import type { Metadata } from "next";
import { Outfit, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import AnimationProvider from "../components/providers/AnimationProvider";
import Header from "@/components/partials/Header";
import Footer from "@/components/partials/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit-loaded",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-google-sans-loaded",
});

export const metadata: Metadata = {
  title: "Eko Ejembi Eko (SAN)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${plusJakartaSans.variable}`}>
      <body className="font-outfit antialiased bg-eee-white">
        <AnimationProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
